import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { linkedinUrl, marketplaceUrl, mentoringUrl, packs, profileUrl, chromeExtensions, otherTools, learn } from './content.ts';
import { contact } from './panels/contact.ts';
import { hero } from './panels/hero.ts';
import { learnHeading, learnTiles, mentor } from './panels/learn.ts';
import { packRows, packsHeading } from './panels/packs.ts';
import { chromeHeading, chromeTiles, toolsHeading, toolTiles } from './panels/products.ts';
import { work } from './panels/work.ts';
import { esc, panelThemes, renderPanel, type Panel } from './svg.ts';

/**
 * Writes every panel as `profile/<name>-<theme>.svg` and assembles `readme.md` from them.
 * The stats panel is written by live.ts, since it needs numbers from GitHub.
 */
interface Tile {
  name: string;
  alt: string;
  href?: string;
}

/** `width` is how much of the README's width a tile takes; tiles that fit side by side share a line. */
interface Tile {
  name: string;
  alt: string;
  width: string;
  href?: string;
}

const panels: Panel[] = [hero, packsHeading, ...packRows, chromeHeading, ...chromeTiles, toolsHeading, ...toolTiles, learnHeading, ...learnTiles, mentor, work, contact];

const tile = ({ name, title }: Panel, width: string, href?: string): Tile => ({ name, alt: title, width, href });
const full = (panel: Panel, href?: string) => tile(panel, '100%', href);

/** One paragraph per section, in reading order. */
const sections: Tile[][] = [
  [full(hero)],
  [{ name: 'stats', alt: 'GitHub: public repositories, stars and followers.', width: '100%', href: profileUrl }],
  [full(packsHeading, marketplaceUrl), ...packRows.map((panel, i) => full(panel, packs[i].url))],
  [full(chromeHeading), ...chromeTiles.map((panel, i) => tile(panel, '49%', chromeExtensions[i].url))],
  [full(toolsHeading), ...toolTiles.map((panel, i) => tile(panel, '49%', otherTools[i].url))],
  [full(learnHeading), ...learnTiles.map((panel, i) => tile(panel, '32%', learn[i].url)), full(mentor, mentoringUrl)],
  [full(work, linkedinUrl)],
  [full(contact)],
];

const picture = ({ name, alt, width, href }: Tile): string => {
  const image = `<picture><source media="(prefers-color-scheme: dark)" srcset="profile/${name}-dark.svg" /><img src="profile/${name}-light.svg" alt="${esc(alt)}" width="${width}" /></picture>`;
  return href ? `<a href="${esc(href)}">${image}</a>` : image;
};

const markup = sections.map((tiles) => `<p align="center">\n${tiles.map((t) => `  ${picture(t)}`).join('\n')}\n</p>`).join('\n\n');

const tools = readFileSync(new URL('./tools.md', import.meta.url), 'utf8').trimEnd();
const readme = `<!-- Generated by \`npm run readme\` from scripts/readme. Edit the generator, not this file. -->

${markup}

📫 [seyyedkhandon.en@gmail.com](mailto:seyyedkhandon.en@gmail.com) · [LinkedIn](${linkedinUrl}) · [GitHub](${profileUrl}) · [Stack Overflow](https://stackoverflow.com/users/12666332/seyyedkhandon) · [YouTube](https://www.youtube.com/c/cafedx_com) · [VS Code Marketplace](${marketplaceUrl}) · [ADPList](${mentoringUrl})

${tools}

<sub>The panels above are SVGs generated by \`npm run readme\`; the stats refresh daily. The source of my portfolio site lives here too: see [DEVELOPMENT.md](DEVELOPMENT.md).</sub>
`;

const root = new URL('../../', import.meta.url);
const out = new URL('profile/', root);
mkdirSync(out, { recursive: true });
for (const panel of panels) {
  for (const theme of panelThemes) {
    writeFileSync(new URL(`${panel.name}-${theme}.svg`, out), renderPanel(panel, theme));
  }
}
writeFileSync(new URL('readme.md', root), readme);
console.log(`Wrote ${panels.length * panelThemes.length} panels to profile/ and readme.md`);
